"""add transfer_verifications table

Revision ID: 02fd7f4442d6
Revises: 93d29788e7ac
Create Date: 2026-08-08 11:45:55.786446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02fd7f4442d6'
down_revision: Union[str, Sequence[str], None] = '93d29788e7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_verifications',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('initiated_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('from_account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('to_account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('otp', sa.String(), nullable=False),
    sa.Column('otp_expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_verifications')
    # ### end Alembic commands ###
