"""add phone verification fields to users

Revision ID: 93d29788e7ac
Revises: fb33a4f484b8
Create Date: 2026-08-08 11:16:35.365334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d29788e7ac'
down_revision: Union[str, Sequence[str], None] = 'fb33a4f484b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('phone_otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_otp_expires_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'phone_verified', server_default=None)

    
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_otp_expires_at')
    op.drop_column('users', 'phone_otp')
    op.drop_column('users', 'phone_verified')
    # ### end Alembic commands ###
