"""add savings goals table

Revision ID: a30b85340339
Revises: 1eeee72cbe9b
Create Date: 2026-08-10 22:59:52.428460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a30b85340339'
down_revision: Union[str, Sequence[str], None] = '1eeee72cbe9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings_goals',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('goal_account_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('source_account_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('contribution_mode', sa.Enum('fixed', 'variable', name='contributionmode'), nullable=True),
    sa.Column('fixed_monthly_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['goal_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['source_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('savings_goals')
    # ### end Alembic commands ###
