"""add national_id_photo_path to users

Revision ID: bb204ecfd0df
Revises: 63ce47d2e440
Create Date: 2026-08-07 15:36:01.377560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb204ecfd0df'
down_revision: Union[str, Sequence[str], None] = '63ce47d2e440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('national_id_photo_path', sa.String(), nullable=True))
    op.drop_column('users', 'national_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('national_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'national_id_photo_path')
    # ### end Alembic commands ###
