"""add address and national_id to users

Revision ID: d19b1dfb3490
Revises: 3f87b564e391
Create Date: 2026-08-05 18:32:17.504160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19b1dfb3490'
down_revision: Union[str, Sequence[str], None] = '3f87b564e391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('national_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'national_id')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
