"""add fraud flags table

Revision ID: d59b13e18e5e
Revises: a30b85340339
Create Date: 2026-08-11 11:29:30.022003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd59b13e18e5e'
down_revision: Union[str, Sequence[str], None] = 'a30b85340339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraud_flags',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('transaction_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='fraudflagseverity'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'cleared', 'confirmed_fraud', name='fraudflagstatus'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fraud_flags')
    # ### end Alembic commands ###
