"""restore national_id column

Revision ID: daac15bf9b0d
Revises: bb204ecfd0df
Create Date: 2026-08-07 15:37:44.155142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daac15bf9b0d'
down_revision: Union[str, Sequence[str], None] = 'bb204ecfd0df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('national_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'national_id')
    # ### end Alembic commands ###
