"""add nickname to accounts

Revision ID: e8fe483715f1
Revises: 08bffbc28ec3
Create Date: 2026-08-05 15:36:06.945235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8fe483715f1'
down_revision: Union[str, Sequence[str], None] = '08bffbc28ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('nickname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'nickname')
    # ### end Alembic commands ###
